### ISSUE TITLE
Meteor startup not work

### ISSUE THREAD

**Issue by stefanocudini** [herrhelms/meteor-leaflet-markercluster#2]
move cose outside of Meteor.startup
this cause error in more cases:
``Uncaught TypeError: L.MarkerClusterGroup is not a function`

**Comment by herrhelms** [comment]
Any way you can tell me about the steps to reproduce the error? 
Elaborate on meteor version + what you did?
What mapbox package are you using?

I just tried this:  
1. meteor create XYZ (v1.1.0.3)
2. meteor add dfischer:meteor-mapbox
3. meteor add herrhelms:meteor-leaflet-markercluster

Everything works like a charm... 

Do you want me to move the code outside of Meteor.startup?
Did you fork this package, tweaked the code and did that resolve your error?

**Comment by stefanocudini** [comment]
In my use case I have a MAP module that use markerclustergroup outside of meteor.startup
_head of my map module:_

``` javascript
//map module, layers,controls e panels
var map = null,
    initialized = false,
    layers = {},
    controls = {};

layers.cluster = new L.MarkerClusterGroup({
...
map = L.map(...
...
```

I think that this is a normal structure for meteor apps

if you wrap the lib inside the meteor startup every modules of the meteor app can be access to this lib only after the dom is ready... I think that it isn't good way.
The modules of an application should not know when the page is ready

**Comment by stefanocudini** [comment]
FYI @mstn

**Comment by herrhelms** [comment]
Ok, good thinking! Thanks for letting me know. I will look into it (but cannot right away) 
You could also just clone, change code, test code and then create a pull request. :) That might be faster

**Comment by stefanocudini** [comment]
Sure!

**Comment by stefanocudini** [comment]
may be you can use this structure of repository:
https://github.com/stefanocudini/meteor-googlemaps-server
using require markercluster from NPM

**Comment by herrhelms** [comment]
Hey @stefanocudini - I'm closing this for now. Hope you found a fix! I'm thinking your issue might be related to the fact that you're talking about googlemaps and not [mapbox](https://www.mapbox.com) integrations?
